### ISSUE TITLE
can not use nodejs build-in module in production

### ISSUE THREAD

**Issue by yuyinws** [vue-terminal/vue-termui#21]
[Reproduction](https://github.com/yuyinws/vue-termui-node-module-issus)
```vue
<script lang="ts" setup>
import path from 'path'
console.log("path",path)
</script>
...
```
`dev`
<img width="369" alt="image" src="https://user-images.githubusercontent.com/38490578/201853218-582b25cd-fe68-4d75-84c9-40b645e31236.png">

`production`
<img width="227" alt="image" src="https://user-images.githubusercontent.com/38490578/201853356-2cf64816-d987-4522-8674-b8e9e23b0a1d.png">

**Comment by posva** [comment]
did you try `import path from 'node:path'`?

**Comment by yuyinws** [comment]
> did you try `import path from 'node:path'`?

Still not work. My node version is 18.8.0.
