### ISSUE TITLE
Bug: the bundle of vtui build can‘t exectue bin command like vtui dev

### ISSUE THREAD

**Issue by Simon-He95** [vue-terminal/vue-termui#26]
<img width="451" alt="image" src="https://user-images.githubusercontent.com/57086651/203493603-bff69304-c6a8-418f-9311-25c548afffd9.png">
After building, I execute packages's bin-cli, but it's nothing happened. Expect to be like dev.

**Comment by posva** [comment]
Tested in a new project and `node dist/main.mjs` runs correctly. You need to provide more information when opening issues, otherwise, you can use the [discord server](https://discord.com/invite/HPVS2AbgXP) to ask questions

**Comment by webfansplz** [comment]
Close it first and then if you can provide more information and reopen it.
